# 프로젝트 영문 번역 (index 기준) — name / desc
TRANS_EN = {
 0:("Restaurant Recommendation Service","A service with an algorithm recommending food/restaurants by location, mood, weather and time."),
 1:("Social Media Platform","A Facebook-style social media service; web + iOS/Android hybrid app."),
 2:("B2C Coupon Solution","A coupon-sales app for offline stores; web + hybrid app."),
 3:("Location-based Social Media","A social network built around specific locations (AWS, Angular, NodeJS, iOS Swift)."),
 4:("Voting / Ranking App","A program to add items on a topic and recommend (vote) on them; NodeJS Socket server."),
 5:("Location-based Chat","A chat app that shares location while messaging."),
 6:("Crypto Exchange Hybrid App","iOS exchange app development and App Store release (Swift)."),
 7:("ERC-20 Token Issuance","Issued 6+ ERC-20 tokens (Solidity, Remix, Metamask) — 100% solo."),
 8:("Blockchain Server Build","Built and integrated BTC/BCH/ADA/ETH coin servers with APIs."),
 9:("Crypto Exchange (VentasBit)","Lead development of the exchange + blockchain integration, operations and new-feature launches; dev lead."),
 10:("Way App","Location-based carpool, sharing economy, second-hand trade and delivery service (iOS/backend)."),
 11:("Dev Team Building","Reorganized R&R for 4 Unity devs and hired designers and front-end engineers."),
 12:("Server Infra & API","Built AWS infra and APIs to upload/query eye-exam device data per member and date."),
 13:("VROR App","App to view eye-exam results per member; passed medical/health review (Swift)."),
 14:("iDoctor Website","Product/team/company intro site with a purchase-inquiry feature (React)."),
 15:("iDoctor Lite Solution","Consumer (B2C) VR eye-exam software; delivered as a KT Super VR build (Pico VR, Unity, C#)."),
 16:("iDoctor Pro Solution","Medical VR eye-exam + PC/tablet mirroring & control versions (Pico VR, Unity, C#)."),
 17:("DB Migration & API Refactor","Refactoring/migration to productize the iDoctor prototype (AWS, Node, MongoDB)."),
 18:("iDoctor Admin","Admin service for activity data, statistics and analytics for client companies (React, Node)."),
 19:("VROR Pico Version","Migration from Fove (discontinued) to standalone Pico VR for the eye-exam software."),
 20:("FutureShow Exhibition","Mapped 4 beam projectors; rendered human shapes via RealSense depth camera (TouchDesigner)."),
 21:("HumanCare","Government project: VR silver-care service with movement and cognitive-rehab games."),
 22:("Smart TV App","2D eye-exam & care service for the Skylife smart-TV app business."),
 23:("BodyDoctor","Physical-function assessment by joint-angle measurement + stretching/exercise management."),
 24:("Cafe Beam-Projector CMS","System to supply, play and manage content for projector-based cafe interiors (Unity + web admin)."),
 25:("Jeju Aerospace Museum Content","6-projector mapped content with sensor-linked interactive games (TouchDesigner, RealSense)."),
 26:("PBL Medical Training Solution","Game-based remote patient-encounter training for Korea Univ. medical students (national exam flow)."),
 27:("iDoctor Admin Rebuild","VOC-driven rebuild — product/result/client management admin (Next.js, Node, MongoDB)."),
 28:("R&D Team Building","Hired engineers to build out the digital-human future business."),
 29:("Digital Human Project","AI human-like chatbot R&D — TTS + Unreal 5 + motion tracking, 16-month roadmap."),
 30:("iDoctor App Renewal","Modernized the iDoctor app into a 2D-deliverable service (Swift)."),
 31:("Elderly Health Monitoring (Y1)","3-year national project: mental/physical monitoring (Azure Kinect, Fitbit; user/worker apps + org web)."),
 32:("Company Website Renewal","Full layout/design/feature renewal for the company's pivoted, diversified products (Next.js)."),
 33:("KT TV App","Selected for KT Smart TV — 2D eye-exam + healing/care video streaming (Android, NodeJS)."),
 34:("Update Manager System","Remote version-update system for Windows/Android/VR devices (Python solution)."),
 35:("PBL Phase 2","Korea Univ. medical training program — outsourced build, process management."),
 36:("Platform Team Building","Hired strategy/designer/front-end/back-end staff for the platform business."),
 37:("Elderly Monitoring (Y2)","Year-3 of the 3-year health-monitoring project — field deployment and testing."),
 38:("Digital Healthcare Platform Plan","Defined requirements, features and layout for the planned platform service (Flutter)."),
 39:("LG U+/Hyundai In-Car Casual Game","Took over a pre-contract build as PM — CDR/WBS, multi-device handling, QC, ops handover. No man-month overrun."),
 40:("FOD Game Service Gov R&D (Y1)","National R&D: team scheduling, device sourcing, wrote the admin spec."),
 41:("Game Platform (Renault AR1)","Game list/performance/quality verification, gamepad usability, provider & client communication."),
 42:("Casual Game — North America","Overseas (NA) expansion, multilingual structure design; CDR/DVT/CVT handling."),
 43:("Genesis Bloomberg WebApp (VOD)","Mass-production WebApp; per-device issues, new VOD spec negotiation and development."),
 44:("Benz Live TV","New IVI Live-TV project kickoff — setup, client handling, schedule/risk management, CDR."),
 45:("FOD Gov R&D (Y2) + Renault PickJoy","Gamepad server build (outsource mgmt), 2 patents filed, 20 games optimized for ~50% CPU cut; PickJoy launch."),
 46:("Benz Live TV (App & Server)","Lead PM — 9 devices DVT, CSMS cybersecurity & pen-test, CVT, Benz OEM(MCR) test passed with zero issues."),
 47:("Genesis Bloomberg WebApp M&S","Maintenance PM — interim reports (ROMS), QC issue analysis, security docs, stable operation."),
 48:("Casual Game 2025 Maintenance","Subscriber monitoring (Hyundai 50k+/Kia 5k+), DVT docs, closeout report."),
 49:("Casual Game 2026 Maintenance","New contract & setup, added security requirements; users Hyundai 120k+/Kia 6.9k."),
 50:("AR1 Game Platform (Renault PickJoy)","20-game CPU optimization, AR2 rollout, payment features, logo redeploy; 10k+ downloads."),
 51:("RKM Payment Integration (PickJoy)","R:Store app integration, payment-confirm API whitelisting; live in the May regular release."),
 52:("PickJoy Multiplayer Game Dev","Multiplayer architecture, gamepad server + multi-packet spec, 6 reworked + 2 new games."),
 53:("PickJoy 2026 Service Ops","Live ops & monitoring, KIA CCNC PoC, FAMOBI stats feature; 18k+ downloads, 43k+ sessions."),
 54:("IITP FOD Game Service Gov R&D","Performance/closeout reports, research notes, final audit presentation completed."),
}
